load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "util",
    hdrs = [
        "include/color.h",
        "include/math_utils.h",
        "include/vector2.h", 
        "include/vector3.h", 
    ],
    visibility = [
        "//core:__subpackages__",
        "//examples:__subpackages__",
    ],
)
