name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: MINGW64
          update: true
          path-type: minimal
          install: >-
            base-devel
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G Ninja

      - name: Build Project
        shell: msys2 {0}
        run: cmake --build build --parallel

      - name: Run tests
        shell: msys2 {0}
        env:
          RINVID_SKIP_OPENGL_TESTS: 1
        run: ctest --test-dir build --output-on-failure -V
