name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git

      - uses: actions/checkout@v2

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: pacman -S mingw-w64-x86_64-sfml mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-gcc --noconfirm
      
      - name: Configure CMake | All
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..

      - name: Build Project
        run: |
          cd build
          make all -j8
